import { slugify } from "./utils";

const aliases = {
  "1sttube":              "First Tube",
  "2001":                 "Also Sprach Zarathustra",
  "20yl":                 "Twenty Years Later",
  "7below":               "Seven Below",
  "atrain":               "Take the 'A' Train",
  "acdc":                 "AC/DC Bag",
  "aditl":                "A Day in the Life",
  "agrace":               "Amazing Grace",
  "alumni":               "Alumni Blues",
  "antelope":             "Run Like an Antelope",
  "ao1":                  "Army of One",
  "asihtos":              "A Song I Heard the Ocean Sing",
  "assefestival":         "The Asse Festival",
  "atr":                  "All Things Reconsidered",
  "avenu":                "Avenu Malkenu",
  "bag":                  "AC/DC Bag",
  "balive":               "Buried Alive",
  "balove":               "Bold As Love",
  "bbfcfm":               "Big Black Furry Creature from Mars",
  "bbjam":                "Big Ball Jam",
  "bbreathes":            "Billy Breathes",
  "bdtnl":                "Backwards Down the Number Line",
  "bekaty":               "Black-Eyed Katy",
  "bgaybl":               "Be Good and You'll Be Lonely",
  "birdwatcher":          "The Birdwatcher",
  "bnb":                  "Breath and Burning",
  "boaf":                 "Birds of a Feather",
  "bocloew":              "The Ballad of Curtis Loew",
  "bomd":                 "Beauty of My Dreams",
  "boogieon":             "Boogie On Reggae Woman",
  "bott":                 "Back on the Train",
  "bouncin'":             "Bouncing Around the Room",
  "bowie":                "David Bowie",
  "cp":                   "Crosseyed and Painless",
  "candp":                "Crosseyed and Painless",
  "caspian":              "Prince Caspian",
  "cdt":                  "Chalk Dust Torture",
  "chalkdust":            "Chalk Dust Torture",
  "char0":                "Character Zero",
  "charzero":             "Character Zero",
  "circus":               "When the Circus Comes",
  "coil":                 "The Squirming Coil",
  "cotm":                 "Crimes of the Mind",
  "ctb":                  "Cars Trucks Buses",
  "crosseyed":            "Crosseyed and Painless",
  "curtainw":             "The Curtain With",
  "curtainwith":          "The Curtain With",
  "curtain":              "The Curtain",
  "curtisloew":           "The Ballad of Curtis Loew",
  "cwalk":                "Camel Walk",
  "daam":                 "Dinner and a Movie",
  "deg":                  "Dave's Energy Guide",
  "destiny":              "Destiny Unbound",
  "dfboy":                "Dog Faced Boy",
  "disease":              "Down with Disease",
  "divided":              "Divided Sky",
  "dogs":                 "The Dogs",
  "dsthings":             "Dogs Stole Things",
  "dststone":             "Daniel Saw the Stone",
  "dtad":                 "Devotion To a Dream",
  "dwd":                  "Down with Disease",
  "fefy":                 "Fast Enough for You",
  "forbins":              "Colonel Forbin's Ascent",
  "fotm":                 "Fire on the Mountain",
  "fts":                  "The Fog That Surrounds",
  "fyf":                  "Fuck Your Face",
  "ggitsky":              "The Great Gig in the Sky",
  "gin":                  "Bathtub Gin",
  "ginseng":              "Ginseng Sullivan",
  "golgi":                "Golgi Apparatus",
  "gtbt":                 "Good Times Bad Times",
  "guelah":               "Guelah Papyrus",
  "h2hell":               "Highway to Hell",
  "halleys":              "Halley's Comet",
  "hbirthday":            "Happy Birthday to You",
  "hmpay":                "How Many People Are You",
  "hood":                 "Harry Hood",
  "horse":                "The Horse",
  "hoty":                 "Hang On to Yourself",
  "hthings":              "Heavy Things",
  "httmoon":              "Halfway to the Moon",
  "hwads":                "The Happy Whip and Dung Song",
  "hydrogen":             "I Am Hydrogen",
  "hyhu":                 "Hold Your Head Up",
  "iatwalrus":            "I Am the Walrus",
  "iawitw":               "I Always Wanted It This Way",
  "idk":                  "I Didn't Know",
  "ifareason":            "I Found a Reason",
  "jbgoode":              "Johnny B. Goode",
  "jibboo":               "Gotta Jibboo",
  "jim":                  "Runaway Jim",
  "jjlc":                 "Jesus Just Left Chicago",
  "kdf":                  "Kill Devil Falls",
  "landlady":             "The Landlady",
  "lcup":                 "Loving Cup",
  "ldboy":                "The Little Drummer Boy",
  "light up":             "Light Up Or Leave Me Alone",
  "lizards":              "The Lizards",
  "lovincup":             "Loving Cup",
  "ltjp":                 "Letter to Jimmy Page",
  "lxl":                  "Limb By Limb",
  "makisupa":             "Makisupa Policeman",
  "mango":                "The Mango Song",
  "mcgrupp":              "McGrupp and the Watchful Hosemasters",
  "melt":                 "Split Open and Melt",
  "mfmf":                 "My Friend, My Friend",
  "mike's":               "Mike's Song",
  "mikes":                "Mike's Song",
  "mist":                 "Mountains in the Mist",
  "mmgamoio":             "My Mind's Got a Mind of Its Own",
  "mockingbird":          "Fly Famous Mockingbird",
  "moma":                 "The Moma Dance",
  "ms1":                  "My Sweet One",
  "msone":                "My Sweet One",
  "mule":                 "Scent of a Mule",
  "nminml":               "No Men In No Man's Land",
  "nomen":                "No Men In No Man's Land",
  "numberline":           "Backwards Down the Number Line",
  "ohkeepa":              "The Oh Kee Pa Ceremony",
  "ohplace":              "The Old Home Place",
  "paug":                 "Weekapaug Groove",
  "peaches":              "Peaches en Regalia",
  "pheart":               "Poor Heart",
  "pitband":              "Playing in the Band",
  "pshippie":             "Prep School Hippie",
  "punch":                "Punch You In the Eye",
  "pyite":                "Punch You In the Eye",
  "quinn":                "Quinn the Eskimo",
  "rr":                   "Rock and Roll",
  "randr":                "Rock and Roll",
  "rnr":                  "Rock and Roll",
  "rrsuicide":            "Rock 'n' Roll Suicide",
  "root":                 "Running Out of Time",
  "roses":                "Roses Are Free",
  "runaway":              "Runaway Jim",
  "sdelilah":             "Samson and Delilah",
  "sadeline":             "Sweet Adeline",
  "sample":               "Sample in a Jar",
  "sass":                 "Scents and Subtle Sounds",
  "sdesign":              "Strange Design",
  "shecaughtthekaty":     "She Caught the Katy and Left Me a Mule to Ride",
  "sia":                  "Saw It Again",
  "siagain":              "Saw It Again",
  "silent":               "Silent in the Morning",
  "slschariot":           "Swing Low, Sweet Chariot",
  "slave":                "Slave to the Traffic Light",
  "sloth":                "The Sloth",
  "sneakinsally":         "Sneakin' Sally Through the Alley",
  "soam":                 "Scent of a Mule",
  "solife":               "Show of Life",
  "ssb":                  "The Star Spangled Banner",
  "ssparty":              "Soul Shakedown Party",
  "stealingtime":         "Stealing Time From the Faulty Plan",
  "stftfp":               "Stealing Time From the Faulty Plan",
  "stwmouse":             "Skippy the Wondermouse",
  "suzy":                 "Suzy Greenberg",
  "theme":                "Theme From the Bottom",
  "timber":               "Timber (Jerry)",
  "tmwsiy":               "The Man Who Stepped Into Yesterday",
  "tpdo":                 "Things People Do",
  "tte":                  "Time Turns Elastic",
  "tweeprise":            "Tweezer Reprise",
  "vlf":                  "The Very Long Fuse",
  "vol":                  "The Vibration of Life",
  "wading":               "Wading in the Velvet Sea",
  "wanight":              "Waiting All Night",
  "wedge":                "The Wedge",
  "weekapaug":            "Weekapaug Groove",
  "witsky":               "Water in the Sky",
  "wlaf":                 "West L.A. Fadeaway",
  "wmggw":                "While My Guitar Gently Weeps",
  "wolfman":              "Wolfman's Brother",
  "wolfmans":             "Wolfman's Brother",
  "wotcave":              "Walls of the Cave",
  "wtu":                  "What's the Use?",
  "wudead":               "Waking Up Dead",
  "yarmouth":             "Yarmouth Road",
  "yem":                  "You Enjoy Myself",
  "ypc":                  "Your Pet Cat",
  "ziggy":                "Ziggy Stardust",
};

function findAlias(term) {
  return aliases[term.toLowerCase().replace(/[^a-z0-9]/g, "")]
    || false;
}

export {
  findAlias
}
